---
name: Create Visualizer Svg
on:
  workflow_dispatch:

jobs:
  update-visualizer:
    name: Update Visualizer
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: 'diagram.svg'
          artifact_name: "my-diagram"
          excluded_paths: 'dist,node_modules'
          branch: 'diagram'
